version: "3.8"

services:
  web:
    container_name: bot
    build: ./app
    volumes:
      - "./app:/app"
    depends_on:
      - db
      - redis
    restart: always
    
  db:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - $PWD/postgre:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - "app/.env"

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    restart: always
    ports:
     - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    env_file:
      - "app/.env"